name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Pack files
      run: |
        touch test
      
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.13
      with: 
        files: test
        tag: 29
