name: MacOS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Install build tools
      run: |
        export CFLAGS="-mmacosx-version-min=10.13"
        brew reinstall --build-from-source automake autoconf libtool pkg-config
    - name: Install libinotify-kqueue
      # brew does not have libinotify package
      run: |
        git clone https://github.com/libinotify-kqueue/libinotify-kqueue
        cd libinotify-kqueue
        export CFLAGS="-mmacosx-version-min=10.13"
        autoreconf -fvi
        ./configure
        make
        sudo make install
        cd ..
    - name: Install sqlite
      # Brew package does not have unlock-notify
      run: |
        wget https://www.sqlite.org/2020/sqlite-autoconf-3310100.tar.gz
        tar xzf sqlite-autoconf-3310100.tar.gz
        cd sqlite-autoconf-3310100
        export CFLAGS='-DSQLITE_ENABLE_UNLOCK_NOTIFY=1 -mmacosx-version-min=10.13'
        ./configure
        make
        sudo make install
        cd ..
    - name: Install gperf and antlr3
      run: |
        export CFLAGS="-mmacosx-version-min=10.13"
        brew reinstall --build-from-source gperf
        pwd
        ls -l
        cd owntone-server/
        pwd
        ls -l
        chmod +x ./scripts/antlr35_install.sh
        ./scripts/antlr35_install.sh -y -p /usr/local
    - name: Install ffmpeg
      # The libbluray ffmpeg dependency fails without the chown (source: stackoverflow)
      run: |
        sudo chown -R $(whoami) $(brew --prefix)/*
        export CFLAGS="-mmacosx-version-min=10.13"
        brew install --build-from-source ffmpeg
    - name: Install other dependencies
      run: |
        export CFLAGS="-mmacosx-version-min=10.13"
        brew reinstall --build-from-source libunistring libmxml confuse libplist sqlite libwebsockets libevent libgcrypt json-c protobuf-c libsodium gnutls pulseaudio openssl

    - name: Configure
      run: |
        export CFLAGS="-mmacosx-version-min=10.13"
        autoreconf -fi
        ./configure --enable-chromecast --enable-lastfm --with-pulseaudio
    - name: Build
      run: |
        # Without setting these env vars the build fails with "fatal error: 'openssl/ssl.h' file not found"
        # (Solution taken from https://github.com/libimobiledevice/libimobiledevice/issues/389#issuecomment-289284190)
        export LD_LIBRARY_PATH=$(brew --prefix openssl)/lib
        export CPATH=$(brew --prefix openssl)/include
        export PKG_CONFIG_PATH=$(brew --prefix openssl)/lib/pkgconfig
        export CFLAGS="-mmacosx-version-min=10.13"
        make
    - name: Install
      run: |
        export CFLAGS="-mmacosx-version-min=10.13"
        sudo make install
        
