name: MacOS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install build tools
      run: brew install automake autoconf libtool pkg-config
    - name: Install libinotify-kqueue
      # brew does not have libinotify package
      run: |
        mkdir -p /usr/local/Cellar/owntone/28.2
        git clone https://github.com/libinotify-kqueue/libinotify-kqueue
        cd libinotify-kqueue
        autoreconf -fvi
        ./configure
        make
        sudo make install
        cd ..
    - name: Install sqlite
      # Brew package does not have unlock-notify
      run: |
        wget https://www.sqlite.org/2020/sqlite-autoconf-3310100.tar.gz
        tar xzf sqlite-autoconf-3310100.tar.gz
        cd sqlite-autoconf-3310100
        export CFLAGS='-DSQLITE_ENABLE_UNLOCK_NOTIFY=1'
        ./configure
        make
        sudo make install
        cd ..
    - name: Install gperf and antlr3
      run: |
        brew install gperf
        chmod +x ./scripts/antlr35_install.sh
        ./scripts/antlr35_install.sh -y -p /usr/local
    - name: Install ffmpeg
      # The libbluray ffmpeg dependency fails without the chown (source: stackoverflow)
      run: |
        sudo chown -R $(whoami) $(brew --prefix)/*
        brew install ffmpeg
    - name: Install other dependencies
      run: brew install libunistring libmxml confuse libplist sqlite libwebsockets libevent libgcrypt json-c protobuf-c libsodium gnutls pulseaudio openssl
    - name: Delete dynamic library
      run: |
        df -h
        sudo rm /usr/local/opt/ffmpeg/lib/libavformat.58.dylib  /usr/local/opt/ffmpeg/lib/libavcodec.58.dylib  /usr/local/opt/ffmpeg/lib/libavutil.56.dylib  /usr/local/opt/ffmpeg/lib/libavfilter.7.dylib  /usr/local/lib/libinotify.0.dylib /usr/local/opt/libgcrypt/lib/libgcrypt.20.dylib  /usr/local/opt/libgpg-error/lib/libgpg-error.0.dylib  /usr/local/lib/libantlr3c.dylib /usr/local/opt/libplist/lib/libplist-2.0.3.dylib  /usr/local/opt/json-c/lib/libjson-c.5.dylib  /usr/local/opt/libmxml/lib/libmxml.dylib  /usr/local/opt/libsodium/lib/libsodium.23.dylib  /usr/lib/libcurl.4.dylib /usr/local/opt/confuse/lib/libconfuse.2.dylib  /usr/local/opt/gnutls/lib/libgnutls.30.dylib  /usr/local/opt/protobuf-c/lib/libprotobuf-c.1.dylib  /usr/local/opt/libevent/lib/libevent_pthreads-2.1.7.dylib /usr/local/opt/libevent/lib/libevent-2.1.7.dylib  /usr/local/opt/libwebsockets/lib/libwebsockets.19.dylib /usr/local/opt/pulseaudio/lib/libpulse.0.dylib  /usr/local/lib/libsqlite3.0.dylib /usr/local/opt/libunistring/lib/libunistring.2.dylib 
    - name: Configure
      run: |
        autoreconf -fi
        ./configure --enable-chromecast --enable-lastfm --with-pulseaudio --prefix=/usr/local/Cellar/owntone/28.2
    - name: Build
      run: |
        # Without setting these env vars the build fails with "fatal error: 'openssl/ssl.h' file not found"
        # (Solution taken from https://github.com/libimobiledevice/libimobiledevice/issues/389#issuecomment-289284190)
        export LD_LIBRARY_PATH=$(brew --prefix openssl)/lib
        export CPATH=$(brew --prefix openssl)/include
        export PKG_CONFIG_PATH=$(brew --prefix openssl)/lib/pkgconfig
        export CFLAGS="-mmacosx-version-min=10.13"
        export LDFLAGS='-static'
        make
    - name: Install
      run: sudo make install

    - name: Pack files
      run: |
        cd ..
        zip -r owntonesrc.zip owntone-server
        zip -r owntonebin.zip /usr/local/Cellar/owntone/28.2
        pwd
        ls -l
        mv *.zip owntone-server/
      
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.13
      with: 
        files: |
          owntonesrc.zip
          owntonebin.zip
        tag_name: v1
