name: MacOS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Install build tools
      run: brew install pkg-config
    - name: pkg-config
      run: /bin/ls -l /usr/local/bin/pkg-config
